### ISSUE TITLE
Upstream changes to discord webhook V2

### ISSUE THREAD

**Issue by jughead0800** [gamemann/Discord-Global-Chat#1]
Changes to Discord API and webhook (moving to version 2.0) breaks the AsyncWebhookAdapter

[https://discordpy.readthedocs.io/en/latest/migrating.html?highlight=asyncwebhookadapter](url)

when trying to launch, the following error: 

`/etc/dgc/Discord-Global-Chat/src# python3 main.py
Traceback (most recent call last):
  File "/etc/dgc/Discord-Global-Chat/src/main.py", line 4, in <module>
    import discordbot
  File "/etc/dgc/Discord-Global-Chat/src/discordbot/__init__.py", line 4, in <module>
    from .discordbot import connect
  File "/etc/dgc/Discord-Global-Chat/src/discordbot/discordbot.py", line 10, in <module>
    from discord import Webhook, AsyncWebhookAdapter
ImportError: cannot import name 'AsyncWebhookAdapter' from 'discord' (/usr/local/lib/python3.9/dist-packages/discord/__init__.py)
`

discordbot.py will have to be updated

(will have a go and see if i can fix it)

**Comment by jughead0800** [comment]
also looks like intents has changed as well

**Comment by gamemann** [comment]
Hey, thank you for bringing this to my attention! I've fixed the bot with commit [47577f5](https://github.com/gamemann/Discord-Global-Chat/commit/47577f5a2be50252a524b2d29cbc9b6b9d6b4fef).

You will need to enable intents for your bot as mentioned [here](https://github.com/gamemann/Discord-Global-Chat#enable-intents).
